export const TYPES = {
    ADD_PRODUCT_TO_LIST: "ADD_PRODUCT_TO_LIST",
    // DELETE_ONE_PRODUCT_FROM_LIST: "DELETE_ONE_PRODUCT_FROM_LIST",
    // DELETE_ALL_FROM_LIST: "DELETE_ALL_FROM_LIST",
    // CLEAR_LIST: "CLEAR_LIST",
    // CALCULATE_PRICE: "CALCULATE_PRICE"
}